include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true  
    prefer_relative_imports: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true

analyzer:
  errors:
    invalid_annotation_target: ignore