name: ui_alumni_mobile
description: "UI Alumni Flutter Mobile App created during the Industrial Project Master's Course at Innopolis University."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  auto_route: ^9.3.0+1
  fast_immutable_collections: ^11.0.3
  fpdart: ^1.1.1
  dio: ^5.8.0+1
  logger: ^2.5.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  latlong2: ^0.9.1
  uuid: ^4.5.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_encrypt_plus: ^2.0.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.0.0
  # idb_sqflite: ^1.3.4
  path_provider: ^2.1.5
  flutter_debouncer: ^2.0.0
  appmetrica_plugin: ^3.1.0
  equatable: ^2.0.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.0+1
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  flutter_gen_runner: ^5.9.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/map/
    - assets/dbs/

flutter_launcher_icons:
  image_path: "assets/icons/iualumni_icon.png"
  android: true
  min_sdk_android: 24
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/iualumni_icon_trans.png"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
