name: ui_alumni_mobile
description: "UI Alumni Flutter Mobile App created during the Industrial Project Master's Course at Innopolis University."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  auto_route: ^9.3.0+1
  fast_immutable_collections: ^11.0.3
  fpdart: ^1.1.1
  dio: ^5.8.0+1
  logger: ^2.5.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  uuid: ^4.5.1
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  sqflite: ^2.4.2
  flutter_debouncer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.0+1
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  flutter_gen_runner: ^5.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/map/
    - assets/dbs/
